import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ThemeProvider } from '@/providers/ThemeProvider';
import { LanguageProvider } from '@/providers/LanguageProvider';
import { ScrollRevealProvider } from '@/providers/ScrollRevealProvider';
import { BackgroundParticles } from '@/components/shared/BackgroundParticles';
import './globals.css';
const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });
export const metadata: Metadata = { title: 'VeriVoice — Multilingual Voice Fact Verification', description: 'A multilingual, explainable voice fact-verification product concept for accessible, evidence-minded information.', keywords: ['fact checking', 'voice verification', 'multilingual fact check', 'UNESCO Youth Hackathon', 'misinformation'], authors: [{ name: 'VeriVoice Team' }], openGraph: { title: 'VeriVoice — Multilingual Voice Fact Verification', description: 'An explainable voice fact-verification product concept.', url: 'https://verivoice.org', siteName: 'VeriVoice', type: 'website' } };
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} suppressHydrationWarning><head><script dangerouslySetInnerHTML={{ __html: `(function(){try{var theme=localStorage.getItem('theme');var prefersDark=window.matchMedia('(prefers-color-scheme: dark)').matches;document.documentElement.classList.toggle('dark',theme==='dark'||(!theme&&prefersDark));}catch(e){document.documentElement.classList.add('dark');}})()` }} /></head><body className="min-h-full bg-white text-zinc-950 dark:bg-zinc-950 dark:text-zinc-50"><div aria-hidden="true" className="vv-backdrop" /><BackgroundParticles className="fixed inset-0 z-0" /><div className="relative z-10"><ThemeProvider><LanguageProvider><ScrollRevealProvider>{children}</ScrollRevealProvider></LanguageProvider></ThemeProvider></div></body></html>; }